import { Skeleton } from "@mui/material";

export default function Loader() {
	return (
		<>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
			<Skeleton
				variant="rectangular"
				height="5%"
				className="mb-2"
			/>
		</>
	);
}
